title : SOMSOM
description: '빅데이터 공부'

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
plugins: [jekyll-gist]
permalink: /:year/:month/:title.html
image:
  background: assets/img/IMG_0527.JPG
